version: 2.1

orbs:
  coveralls: coveralls/coveralls@1.0.5
  heroku: circleci/heroku@0.0.10

jobs:
  build:
    docker:
      - image: circleci/node:10.16.3
    working_directory: ~/repo
    steps:
      - checkout
      # install dependencies
      - run:
          name: Install Dependencies
          command: npm install && make test-coverage
      - coveralls/upload
      - run:
          name: Run tests
          command: npm run test


